### ISSUE TITLE
Create Flask API start script

### ISSUE THREAD

**Issue by greenmoss** [Doveps/old_savant#4]
Goal: run a script to start Flask

Add the script to this repository

**Comment by JosiahRegencia** [comment]
Hi, so I finished up to the 4th task. Though I didn't close the 4th issue yet. I used stored procedures instead of using Django. I think I'm more used to it that way. I'm not sure, however, about the 5th issue. As of the code I added, there isn't still a connection between bassist and savant. So when I run scans, it doesn't save on postgres yet. I'm not sure how to extract the data from parser.parser yet.

**Comment by greenmoss** [comment]
OK, thanks. I'd like to see tickets linked to commits or pull requests. Trying that now:

https://github.com/Doveps/savant/commit/7f62ba23608598c442542639b68c6a11c0436702

**Comment by greenmoss** [comment]
OK, I definitely would like to see pull requests. Do you know how to open a new PR, link to a ticket, and merge/close?

**Comment by JosiahRegencia** [comment]
No. I don't think I've tried that before
